services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: simakov
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgress
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

#  jaeger:
#    container_name: jaeger
#    image: jaegertracing/all-in-one:latest
#    environment:
#      COLLECTOR_OTLP_ENABLED: true
#      COLLECTOR_ZIPKIN_HOST_PORT: 9411
#    ports:
#      - "16686:16686"
#      - "14250:14250"

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: