server:
  port: 8080

spring:
  application:
    name: customer-service
  datasource:
    username: simakov
    url: jdbc:postgresql://localhost:5432/customer
    password: 123456
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

rabbitmq:
  exchanges:
    internal: internal.exchange
  routing-keys:
    internal-notification: internal.notification.rk